steps:
# build the container
- name: 'docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/gcpdevops','.']
# push the container to the registry
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]
# deploy the container to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "Configuring kubectl"
    gcloud container clusters get-credentials dev-platform --zone us-central1-c --project $PROJECT_ID
    echo "Creating namespace if not exists"
    kubectl get namespace gcp-devops-prod || kubectl create namespace gcp-devops-prod
    echo "Applying Kubernetes configurations"
    kubectl apply -f gke.yaml
  env:
  - CLOUDSDK_COMPUTE_ZONE=us-central1-c
  - CLOUDSDK_CONTAINER_CLUSTER=dev-platform
serviceAccount: 'my-service-account-1@sacred-footing-421417.iam.gserviceaccount.com'
options:
  logging: 'CLOUD_LOGGING_ONLY'
