steps:
# build the container
- name: 'docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/gcpdevops','.']
# push the container to the registry
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]
# deploy the container to GKE
- name: "gcr.io/cloud-builders/kubectl"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --namespace=gcp-devops-prod
  env:
  - CLOUDSDK_COMPUTE_ZONE=us-central1-c
  - CLOUDSDK_CONTAINER_CLUSTER=dev-platform
serviceAccount: 'my-service-account-1@sacred-footing-421417.iam.gserviceaccount.com'
options:
  logging: 'CLOUD_LOGGING_ONLY'
