steps:
- name: 'docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/gcpdevops','.']
images:
  - 'gcr.io/$PROJECT_ID/gcpdevops'
serviceAccount: 'my-service-account-1@sacred-footing-421417.iam.gserviceaccount.com'